# Generated by Django 5.0.4 on 2024-04-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
