# Generated by Django 5.0.4 on 2024-04-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_alter_spot_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='down',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='up',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='down',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='up',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
