# Generated by Django 5.0.4 on 2024-04-24 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spots", "0003_comment_down_comment_up_post_down_post_up"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
    ]
