# Generated by Django 5.0.4 on 2024-04-24 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spots", "0007_alter_post_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
    ]
